services:
  eureka-server:
    build: ./backend/eureka-server
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - mariadb

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8088:8088"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - eureka-server
      - keycloak

  user-profile-management:
    build: ./backend/user-profile-management
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/user_profile_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - mariadb
      - eureka-server
      - kafka

  medical-records-management:
    build: ./backend/medical-records-management
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/medical_records_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - mariadb
      - eureka-server
      - kafka

  billing-management:
    build: ./backend/billing_management
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/billing_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - mariadb
      - eureka-server
      - kafka

  notification-management:
    build: ./backend/notification_management
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/notification_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - mariadb
      - eureka-server
      - kafka

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8086:8086"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - eureka-server
      - keycloak

  mariadb:
    image: mariadb:11.3
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    command: start-dev
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

volumes:
  mariadb_data:
