apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: default
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30088