apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: hani016/medical-records-management-system-auth-service
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        ports:
        - containerPort: 8086