version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"       # Port web Jenkins personnalisé
      - "50000:50000"     # Port agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Accès Docker hôte
    restart: unless-stopped

volumes:
  jenkins_home:
