package com.corilus.billing_management.enums;

public enum HistoryType {
    APPOINTMENT_UPDATE,
    MEDICAL_RECORD_UPDATE,
    MAIN_NOTE_UPDATED,
    INVOICE_GENERATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    DOCUMENT_SHARED,
    NOTE_CREATED,
    NOTE_DELETED,
    MEDICAL_RECORD_DELETED,
    APPOINTMENT_ADDED,
    APPOINTMENT_DELETED,
    NOTE_UPDATED,
    DOCUMENT_UPDATED,
    APPOINTMENT_UPDATED,
    NOTE_UPDATEDD,
    DOCUMENT_NOTE_UPDATED,
    INVOICE_CREATED,
    INVOICE_UPDATED,
    INVOICE_DELETED,
    INVOICE_PAID,
    INVOICE_CANCELLED,
    I_UPD
}
